project:
  type: website
  output-dir: docs

website:
  title: "DS4SJ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu: 
          - contributing.qmd
          - team.qmd
          - acknowledgements.qmd
      - href: notes.qmd
        text: Notes
      - text: Resources
        menu: 
          - resource-pages/papers.qmd
          - resource-pages/pedagogy.qmd
          - resource-pages/people.qmd
          - resource-pages/organizations.qmd
          - resource-pages/theory.qmd
          - resource-pages/other-resources.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: 
      - custom.css
    toc: true



